server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  security:
    user:
      name: semusings
      password: semusings
openfga:
  api-url: http://localhost:4000
  store-name: semusings
application:
  springdoc:
    title: Order API
    version: 0.0.1
    description: Microservice-based order management system - Order API
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0
    external-doc:
      description: Github - Source Code
      url: "https://github.com/semusings/spring-boot-demo"