name: spring-boot-demo
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  openfga:
    extends:
      file: ./openfga.yml
      service: openfga
  openfgaimport:
    extends:
      file: ./openfga.yml
      service: openfgaimport