### Create order
POST http://127.0.0.1:9091/api/orders
Authorization: Bearer {{$auth.token("bearer_token")}}

### List orders
GET http://127.0.0.1:9091/api/orders
Authorization: Bearer {{$auth.token("bearer_token")}}
